# Setup
title: KIM TAE SEUNG
description: I hope we can grow together.
url: https://tskim9926.github.io
avatar: /avatar.jpeg
paginate: 5
permalink: pretty
cover_image: /bg.jpeg

# About 페이지 링크 설정
about: /about/   

# Plugins
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md            # README.md를 제외
  - scripts/
  - not-pure-poole.gemspec

twitter:
  username: tskim9926
  card: summary_large_image
logo: logo.png
social:
  name: Taeseung Kim
  links:
    - url: https://github.com/tskim9926
      title: "GitHub"
      icon: "fab fa-github"  # GitHub 아이콘
    - url: "mailto:tskim9926@gmail.com"
      title: "Email"
      icon: "fas fa-envelope"  # 이메일 아이콘
    - url: https://tskim9926.tistory.com/
      title: "Blog"
      icon: "fas fa-blog"  # 블로그 아이콘 (적절한 아이콘 클래스를 선택)

    
# SEO 및 기타 설정
lang: en

# Sass 설정
sass:
  sass_dir: _sass
  style: :compressed

# 옵션

# Google Analytics 추적 활성화하려면 주석 해제하고 값 입력
# google_analytics: UA-000000-0

# Disqus 사용을 위해 주석 해제하고 값 입력
# disqus: xxxxxx

# 블로그 게시물 작성자 정보
author:
  name: Taeseung Kim
  url: https://tskim9926.tistory.com/
  email: tskim9926@gmail.com
  bio: |
    Taeseung Kim, a Software Engineer specializing in semiconductor manufacturing. 
    Since August 2020, I have been developing systems and equipment that control lasers and scanners 
    based on recipe data to shape patterns on wafers.
    I graduated with a Bachelor's degree in Electronic Engineering from Korea Polytechnic University.
