# Setup
title: KIM TAE SEUNG
description: I hope we can grow together.
url: https://tskim9926.github.io
avatar: /avatar.jpeg
paginate: 5
permalink: pretty
cover_image: /bg.jpeg

# About 페이지 링크 설정
about: /about.md

# Plugins
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md            # README.md를 제외
  - scripts/
  - not-pure-poole.gemspec

# Social Links
twitter:
  username: tskim9926
  card: summary_large_image
logo: logo.png
social:
  name: Taeseung Kim
  links:
    - url: https://github.com/tskim9926
      title: "GitHub"
      icon: "fab fa-github"
    - url: "mailto:tskim9926@gmail.com"
      title: "Email"
      icon: "fas fa-envelope"

# SEO 및 기타 설정
lang: en

# Sass 설정
sass:
  sass_dir: _sass
  style: :compressed

# Google Analytics 설정
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-WRRCRTN5TC"
    anonymize_ip: false  # IP 익명화 설정 (필요에 따라 true로 변경 가능)

# Google AdSense 설정
adsense:
  enabled: true  # AdSense 활성화 여부
  client_id: "ca-pub-7555924334853398"  # 본인의 애드센스 퍼블리셔 ID 입력

# 블로그 게시물 작성자 정보
author:
  name: Taeseung Kim
  url: https://tskim9926.github.io
  email: tskim9926@gmail.com
  bio: |
     Jekyll 블로그를 운영하며 기술과 경험을 공유합니다.

# 네비게이션 메뉴 설정
nav:
  - title: "Blog"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Post"
    url: "/post/"
